### ISSUE TITLE
chirp-connect-release.aar seems to have been renamed

### ISSUE THREAD

**Issue by James-deWitt** [AlexanderKub/unity-chirp-plugin#3]
in ChirpSDK-Android-3.6.1 there is no file named "chirp-connect-release.aar"

Has it been renamed as "chirpsdk-release.aar"?

**Comment by AlexanderKub** [comment]
> in ChirpSDK-Android-3.6.1 there is no file named "chirp-connect-release.aar"
> 
> Has it been renamed as "chirpsdk-release.aar"?

Yeah, you are totally right, I already published a new release. Sorry for no answer a long time, it was some problems with notifications in this repository. I hope it's not too late)
