### ISSUE TITLE
NullReferenceException when calling ChirpPlugin.InitSDK

### ISSUE THREAD

**Issue by James-deWitt** [AlexanderKub/unity-chirp-plugin#4]
After following the setup introductions for getting the example working and  building it to an android device, I am getting a null reference exception after calling ChirpPlugin.InitSDK

> AndroidPlayer(ADB@127.0.0.1:34999)</i> NullReferenceException: Object reference not set to an instance of an object
  at ChirpPlugin.InitSDK (System.String key, System.String secret, System.String config) [0x00016] in D:\Development\Unity Projects\BallPassingGame\BallPassingGame\Assets\ChirpIO\Plugins\ChirpPlugin.cs:136 
  at TestPlugin.ChirpInitSDK () [0x00069] in D:\Development\Unity Projects\BallPassingGame\BallPassingGame\Assets\ChirpIO\Examples\TestPlugin.cs:62 
UnityEngine.DebugLogHandler:Internal_LogException()
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
TestPlugin:ChirpInitSDK() (at D:\Development\Unity Projects\BallPassingGame\BallPassingGame\Assets\ChirpIO\Examples\TestPlugin.cs:66)
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Button.cs:66)
UnityEngine.UI.Button:OnPointerClick(PointerEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\ExecuteEvents.cs:261)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:371)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:270)
UnityEngine.EventSystems.StandaloneInputModule:Process() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:253)
UnityEngine.EventSystems.EventSystem:Update() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\EventSystem.cs:377)

Unity 2018.3.4f1 Personal
Android API level 16

Tried it with both chirp-connect-release.aar and chirpsdk-release.aar

**Comment by AlexanderKub** [comment]
Referenced to #3
